import { ids } from './ids';

export const notificationsSeed = [
  {
    sppgId: ids.sppg.kebayoran,
    schoolId: ids.schools.kebayoran01,
    type: 'notification' as const,
    message: 'SDN Kebayoran Baru 01 mengonfirmasi seluruh paket diterima lengkap.',
    status: 'received' as const,
    createdAt: new Date('2026-05-01T10:30:00+07:00'),
  },
  {
    sppgId: ids.sppg.kebayoran,
    schoolId: ids.schools.smp12,
    type: 'complaint' as const,
    message: 'SMPN 12 Jakarta melaporkan keterlambatan distribusi sekitar 20 menit.',
    status: 'new' as const,
    createdAt: new Date('2026-05-01T11:08:00+07:00'),
  },
  {
    sppgId: ids.sppg.kebayoran,
    schoolId: ids.schools.petogogan05,
    type: 'feedback' as const,
    message: 'SDN Petogogan 05 meminta tambahan sendok cadangan untuk distribusi berikutnya.',
    status: 'new' as const,
    createdAt: new Date('2026-05-01T11:45:00+07:00'),
  },
  {
    sppgId: ids.sppg.menteng,
    schoolId: ids.schools.menteng01,
    type: 'notification' as const,
    message: 'SDN Menteng 01 memberi rating 5 untuk menu ikan tongkol dan buah jeruk.',
    status: 'reviewed' as const,
    createdAt: new Date('2026-04-30T10:38:00+07:00'),
  },
  {
    sppgId: ids.sppg.menteng,
    schoolId: ids.schools.gondangdia03,
    type: 'feedback' as const,
    message: 'SDN Gondangdia 03 mencatat rasa capcay agak asin.',
    status: 'received' as const,
    createdAt: new Date('2026-04-29T11:18:00+07:00'),
  },
  {
    sppgId: ids.sppg.matraman,
    schoolId: ids.schools.pisangan07,
    type: 'notification' as const,
    message: 'SDN Pisangan Baru 07 menerima paket sebelum jam istirahat.',
    status: 'reviewed' as const,
    createdAt: new Date('2026-05-01T10:15:00+07:00'),
  },
  {
    sppgId: ids.sppg.matraman,
    schoolId: ids.schools.smp97,
    type: 'feedback' as const,
    message: 'SMPN 97 Jakarta meminta porsi nasi lebih padat untuk siswa SMP.',
    status: 'received' as const,
    createdAt: new Date('2026-04-30T11:55:00+07:00'),
  },
  {
    sppgId: ids.sppg.priok,
    schoolId: ids.schools.sunter09,
    type: 'complaint' as const,
    message: 'SDN Sunter Agung 09 menemukan tiga tutup paket kurang rapat.',
    status: 'new' as const,
    createdAt: new Date('2026-05-01T11:23:00+07:00'),
  },
  {
    sppgId: ids.sppg.priok,
    schoolId: ids.schools.smp95,
    type: 'notification' as const,
    message: 'SMPN 95 Jakarta mengonfirmasi menu sesuai rencana mingguan.',
    status: 'reviewed' as const,
    createdAt: new Date('2026-04-30T10:25:00+07:00'),
  },
  {
    sppgId: ids.sppg.cengkareng,
    schoolId: ids.schools.smp45,
    type: 'complaint' as const,
    message: 'SMPN 45 Jakarta melaporkan pengiriman datang 15 menit setelah jadwal.',
    status: 'new' as const,
    createdAt: new Date('2026-04-30T11:40:00+07:00'),
  },
];
