import { ids } from './ids';

export const reportsSeed = [
  {
    schoolId: ids.schools.kebayoran01,
    sppgId: ids.sppg.kebayoran,
    note: 'Porsi diterima lengkap, suhu makanan masih hangat, dan siswa menyukai menu soto ayam.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-05-01T10:25:00+07:00'),
  },
  {
    schoolId: ids.schools.smp12,
    sppgId: ids.sppg.kebayoran,
    note: 'Distribusi terlambat 20 menit karena kepadatan lalu lintas di sekitar sekolah.',
    rating: 4,
    status: 'received' as const,
    submittedAt: new Date('2026-05-01T11:05:00+07:00'),
  },
  {
    schoolId: ids.schools.petogogan05,
    sppgId: ids.sppg.kebayoran,
    note: 'Menu sesuai rencana, namun jumlah sendok cadangan perlu ditambah.',
    rating: 4,
    status: 'submitted' as const,
    submittedAt: new Date('2026-05-01T11:40:00+07:00'),
  },
  {
    schoolId: ids.schools.menteng01,
    sppgId: ids.sppg.menteng,
    note: 'Anak-anak sangat antusias dengan buah jeruk dan lauk ikan tongkol.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-04-30T10:35:00+07:00'),
  },
  {
    schoolId: ids.schools.smp1,
    sppgId: ids.sppg.menteng,
    note: 'Kualitas makanan baik, kemasan rapi, dan tidak ada porsi rusak.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-04-30T10:55:00+07:00'),
  },
  {
    schoolId: ids.schools.gondangdia03,
    sppgId: ids.sppg.menteng,
    note: 'Sayur capcay agak asin untuk sebagian siswa kelas rendah.',
    rating: 4,
    status: 'received' as const,
    submittedAt: new Date('2026-04-29T11:15:00+07:00'),
  },
  {
    schoolId: ids.schools.pisangan07,
    sppgId: ids.sppg.matraman,
    note: 'Jumlah paket sesuai daftar hadir dan pengiriman tiba sebelum jam istirahat.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-05-01T10:10:00+07:00'),
  },
  {
    schoolId: ids.schools.smp97,
    sppgId: ids.sppg.matraman,
    note: 'Beberapa paket nasi kurang padat untuk siswa SMP, mohon dievaluasi.',
    rating: 3,
    status: 'received' as const,
    submittedAt: new Date('2026-04-30T11:50:00+07:00'),
  },
  {
    schoolId: ids.schools.utanKayu01,
    sppgId: ids.sppg.matraman,
    note: 'Menu bervariasi dan buah diterima dalam kondisi segar.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-04-29T10:45:00+07:00'),
  },
  {
    schoolId: ids.schools.sunter09,
    sppgId: ids.sppg.priok,
    note: 'Ada tiga paket dengan tutup kurang rapat, sudah dipisahkan oleh petugas sekolah.',
    rating: 3,
    status: 'submitted' as const,
    submittedAt: new Date('2026-05-01T11:20:00+07:00'),
  },
  {
    schoolId: ids.schools.smp95,
    sppgId: ids.sppg.priok,
    note: 'Paket tiba tepat waktu dan menu sesuai dengan daftar menu mingguan.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-04-30T10:20:00+07:00'),
  },
  {
    schoolId: ids.schools.kebonBawang03,
    sppgId: ids.sppg.priok,
    note: 'Porsi lauk cukup, namun siswa meminta variasi buah selain pisang.',
    rating: 4,
    status: 'received' as const,
    submittedAt: new Date('2026-04-29T10:40:00+07:00'),
  },
  {
    schoolId: ids.schools.cengkareng04,
    sppgId: ids.sppg.cengkareng,
    note: 'Distribusi tetap berjalan baik selama dapur menjalani perawatan alat masak.',
    rating: 4,
    status: 'received' as const,
    submittedAt: new Date('2026-05-01T10:30:00+07:00'),
  },
  {
    schoolId: ids.schools.smp45,
    sppgId: ids.sppg.cengkareng,
    note: 'Kemasan bersih dan rapi, tetapi pengiriman datang 15 menit setelah jadwal.',
    rating: 4,
    status: 'submitted' as const,
    submittedAt: new Date('2026-04-30T11:35:00+07:00'),
  },
  {
    schoolId: ids.schools.rawaBuaya01,
    sppgId: ids.sppg.cengkareng,
    note: 'Siswa menyukai menu nasi kuning dan lauk ayam suwir pada distribusi terakhir.',
    rating: 5,
    status: 'reviewed' as const,
    submittedAt: new Date('2026-04-29T10:30:00+07:00'),
  },
];
