import { ids } from './ids';

export const sppgSeed = [
  {
    id: ids.sppg.kebayoran,
    userId: ids.users.sppgKebayoran,
    name: 'SPPG Kebayoran Baru',
    sppgCode: 'SPPG-JKS-001',
    address: 'Jl. Melawai Raya No. 12, Kebayoran Baru, Jakarta Selatan',
    personInCharge: 'Dewi Lestari',
    capacityPerDay: 5200,
    status: 'active' as const,
    lat: '-6.2441000',
    lng: '106.8005000',
  },
  {
    id: ids.sppg.menteng,
    userId: ids.users.sppgMenteng,
    name: 'SPPG Menteng Berseri',
    sppgCode: 'SPPG-JKP-002',
    address: 'Jl. HOS Cokroaminoto No. 84, Menteng, Jakarta Pusat',
    personInCharge: 'Arif Prasetyo',
    capacityPerDay: 4600,
    status: 'active' as const,
    lat: '-6.1954000',
    lng: '106.8322000',
  },
  {
    id: ids.sppg.matraman,
    userId: ids.users.sppgMatraman,
    name: 'SPPG Matraman Sehat',
    sppgCode: 'SPPG-JKT-003',
    address: 'Jl. Matraman Raya No. 55, Matraman, Jakarta Timur',
    personInCharge: 'Nurul Hasanah',
    capacityPerDay: 4100,
    status: 'active' as const,
    lat: '-6.2030000',
    lng: '106.8625000',
  },
  {
    id: ids.sppg.priok,
    userId: ids.users.sppgPriok,
    name: 'SPPG Tanjung Priok Bahari',
    sppgCode: 'SPPG-JKU-004',
    address: 'Jl. Yos Sudarso No. 18, Tanjung Priok, Jakarta Utara',
    personInCharge: 'Maya Kartika',
    capacityPerDay: 3800,
    status: 'active' as const,
    lat: '-6.1286000',
    lng: '106.8708000',
  },
  {
    id: ids.sppg.cengkareng,
    userId: ids.users.sppgCengkareng,
    name: 'SPPG Cengkareng Peduli',
    sppgCode: 'SPPG-JKB-005',
    address: 'Jl. Outer Ring Road No. 7, Cengkareng, Jakarta Barat',
    personInCharge: 'Rizky Firmansyah',
    capacityPerDay: 3400,
    status: 'maintenance' as const,
    lat: '-6.1448000',
    lng: '106.7299000',
  },
];
